### ISSUE TITLE
Can't load overworld

### ISSUE THREAD

**Issue by bashbers** [TheStaticVoid/StaTech-Industry#163]
Error log
```
minecraft  | [11:01:13] [Server thread/INFO]: Starting Minecraft server on *:25565
minecraft  | [11:01:13] [Server thread/INFO]: Using epoll channel type
minecraft  | [11:01:13] [Server thread/INFO]: Preparing level "world"
minecraft  | [11:01:14] [Server thread/INFO]: Loading Teams Data
minecraft  | [11:01:14] [Server thread/INFO]: Finished Loading Teams Data
minecraft  | [11:01:14] [Server thread/INFO]: "./config/byg/surface_rules/nether_surface_rules.json5" was read.
minecraft  | [11:01:14] [Server thread/INFO]: "./config/byg/surface_rules/end_surface_rules.json5" was read.
minecraft  | [11:01:14] [Server thread/INFO]: "./config/byg/surface_rules/overworld_surface_rules.json5" was read.
minecraft  | [11:01:14] [Server thread/INFO]: Loading dimension "minecraft:the_nether" with biome source: "byg:nether".
minecraft  | [11:01:14] [Server thread/INFO]: "./config/byg/surface_rules/nether_surface_rules.json5" was read.
minecraft  | [11:01:14] [Server thread/INFO]: "./config/byg/surface_rules/end_surface_rules.json5" was read.
minecraft  | [11:01:14] [Server thread/INFO]: "./config/byg/surface_rules/overworld_surface_rules.json5" was read.
minecraft  | [11:01:14] [Server thread/INFO]: Loading dimension "minecraft:the_end" with biome source: "byg:end".
minecraft  | [11:01:14] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
minecraft  | [11:01:16] [Netty Epoll Server IO #1/INFO]: Mixing server.MixinServerboundChatPacket from nochatreports.mixins.json into net.minecraft.class_2797
minecraft  | [11:01:16] [Netty Epoll Server IO #1/INFO]: Mixing common.MixinServerStatusSerializer from nochatreports.mixins.json into net.minecraft.class_2926$class_2929
minecraft  | [11:01:33] [Server thread/INFO]: Time elapsed: 28957582317 ms
minecraft  | [11:01:33] [Server thread/INFO]: [MemoryLeakFix] Attempting to ForceLoad All Mixins and clear cache
minecraft  | [11:01:33] [Server thread/ERROR]: Encountered an unexpected exception
minecraft  | java.lang.NoClassDefFoundError: net/minecraft/class_746
minecraft  |    at java.lang.Class.forName0(Native Method) ~[?:?]
minecraft  |    at java.lang.Class.forName(Unknown Source) ~[?:?]
minecraft  |    at net.fabricmc.loader.impl.launch.knot.MixinServiceKnot.findClass(MixinServiceKnot.java:96) ~[fabric-loader-0.14.21.jar:?]
minecraft  |    at org.spongepowered.asm.mixin.transformer.MixinProcessor.audit(MixinProcessor.java:254) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
minecraft  |    at org.spongepowered.asm.mixin.transformer.MixinTransformer.audit(MixinTransformer.java:171) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
minecraft  |    at org.spongepowered.asm.mixin.MixinEnvironment.audit(MixinEnvironment.java:1425) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
minecraft  |    at ca.fxco.memoryleakfix.fabric.MemoryLeakFixFabric.internalForceLoadAllMixinsAndClearSpongePoweredCache(MemoryLeakFixFabric.java:40) ~[memoryleakfix-fabric-1.17+-1.0.0.jar:?]
minecraft  |    at ca.fxco.memoryleakfix.fabric.MemoryLeakFixFabric.forceLoadAllMixinsAndClearSpongePoweredCache(MemoryLeakFixFabric.java:32) ~[memoryleakfix-fabric-1.17+-1.0.0.jar:?]
minecraft  |    at net.minecraft.server.MinecraftServer.handler$dda000$memoryleakfix$memoryLeakFix$loadAllMixinsServerSide(MinecraftServer.java:11270) ~[server-intermediary.jar:?]
minecraft  |    at net.minecraft.server.MinecraftServer.method_3735(MinecraftServer.java:330) ~[server-intermediary.jar:?]
minecraft  |    at net.minecraft.class_3176.method_3823(class_3176.java:172) ~[server-intermediary.jar:?]
minecraft  |    at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:636) ~[server-intermediary.jar:?]
minecraft  |    at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[server-intermediary.jar:?]
minecraft  |    at java.lang.Thread.run(Unknown Source) [?:?]
minecraft  | Caused by: java.lang.ClassNotFoundException: net.minecraft.class_746
minecraft  |    at jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source) ~[?:?]
minecraft  |    at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
minecraft  |    at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.14.21.jar:?]
minecraft  |    at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.21.jar:?]
minecraft  |    at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
minecraft  |    ... 14 more
minecraft  | [11:01:33] [Server thread/ERROR]: This crash report has been saved to: /data/./crash-reports/crash-2023-06-02_11.01.33-server.txt
minecraft  | [11:01:33] [Server thread/INFO]: Shutting down the config watcher executor
minecraft  | [11:01:33] [Server thread/INFO]: Shutting down backup cleaning executor
minecraft  | [11:01:33] [Server thread/INFO]: Shutting down backup executor
minecraft  | [11:01:33] [Server thread/INFO]: =========Checking everything is shut down============
minecraft  | [11:01:33] [Server thread/INFO]: [STDERR]: java.lang.NullPointerException: Cannot invoke "net.creeperhost.ftbbackups.org.quartz.Scheduler.isShutdown()" because "net.creeperhost.ftbbackups.FTBBackups.scheduler" is null
minecraft  | [11:01:33] [Server thread/INFO]: [STDERR]:         at net.creeperhost.ftbbackups.FTBBackups.killOutThreads(FTBBackups.java:131)
minecraft  | [11:01:33] [Server thread/INFO]: [STDERR]:         at net.creeperhost.ftbbackups.FTBBackups.lambda$init$1(FTBBackups.java:46)
minecraft  | [11:01:33] [Server thread/INFO]: [STDERR]:         at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(Unknown Source)
minecraft  | [11:01:33] [Server thread/INFO]: [STDERR]:         at dev.architectury.event.EventFactory.invokeMethod(EventFactory.java:53)
minecraft  | [11:01:33] [Server thread/INFO]: [STDERR]:         at dev.architectury.event.EventFactory$1.handleInvocation(EventFactory.java:62)
minecraft  | [11:01:33] [Server thread/INFO]: [STDERR]:         at com.google.common.reflect.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:89)
minecraft  | [11:01:33] [Server thread/INFO]: [STDERR]:         at jdk.proxy2/jdk.proxy2.$Proxy141.stateChanged(Unknown Source)
minecraft  | [11:01:33] [Server thread/INFO]: [STDERR]:         at dev.architectury.event.fabric.EventHandlerImpl.lambda$registerCommon$10(EventHandlerImpl.java:67)
minecraft  | [11:01:33] [Server thread/INFO]: [STDERR]:         at net.fabricmc.fabric.api.event.lifecycle.v1.ServerLifecycleEvents.lambda$static$4(ServerLifecycleEvents.java:63)
minecraft  | [11:01:33] [Server thread/INFO]: [STDERR]:         at net.minecraft.server.MinecraftServer.handler$bpf000$fabric-lifecycle-events-v1$beforeShutdownServer(MinecraftServer.java:7306)
minecraft  | [11:01:33] [Server thread/INFO]: [STDERR]:         at net.minecraft.server.MinecraftServer.method_3782(MinecraftServer.java)
minecraft  | [11:01:33] [Server thread/INFO]: [STDERR]:         at net.minecraft.class_3176.method_3782(class_3176.java:547)
minecraft  | [11:01:33] [Server thread/INFO]: [STDERR]:         at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
minecraft  | [11:01:33] [Server thread/INFO]: [STDERR]:         at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
minecraft  | [11:01:33] [Server thread/INFO]: [STDERR]:         at java.base/java.lang.Thread.run(Unknown Source)
minecraft  | [11:01:33] [Server thread/INFO]: Stopping server
minecraft  | [11:01:33] [Server thread/INFO]: Saving players
minecraft  | [11:01:33] [Server thread/INFO]: Saving worlds
minecraft  | [11:01:36] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world]'/minecraft:overworld
minecraft  | [11:01:39] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world]'/ad_astra:moon_orbit
minecraft  | [11:01:39] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world]'/minecraft:the_nether
minecraft  | [11:01:39] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world]'/ad_astra:mercury
minecraft  | [11:01:39] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world]'/ad_astra:venus_orbit
minecraft  | [11:01:39] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world]'/ad_astra:venus
minecraft  | [11:01:39] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world]'/minecraft:the_end
minecraft  | [11:01:39] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world]'/ad_astra:mars
minecraft  | [11:01:39] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world]'/twilightforest:twilight_forest
minecraft  | [11:01:39] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world]'/spectrum:deeper_down_dimension
minecraft  | [11:01:39] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world]'/ad_astra:mars_orbit
minecraft  | [11:01:39] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world]'/ad_astra:mercury_orbit
minecraft  | [11:01:39] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world]'/ad_astra:moon
minecraft  | [11:01:39] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world]'/ad_astra:glacio
minecraft  | [11:01:39] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world]'/ad_astra:glacio_orbit
minecraft  | [11:01:39] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world]'/ad_astra:earth_orbit
minecraft  | [11:01:39] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world]'/spellbladenext:glassocean
minecraft  | [11:01:39] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world]'/ae2:spatial_storage
minecraft  | [11:01:39] [Server thread/INFO]: ThreadedAnvilChunkStorage (world): All chunks are saved
minecraft  | [11:01:39] [Server thread/INFO]: ThreadedAnvilChunkStorage (moon_orbit): All chunks are saved
minecraft  | [11:01:39] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
minecraft  | [11:01:39] [Server thread/INFO]: ThreadedAnvilChunkStorage (mercury): All chunks are saved
minecraft  | [11:01:39] [Server thread/INFO]: ThreadedAnvilChunkStorage (venus_orbit): All chunks are saved
minecraft  | [11:01:39] [Server thread/INFO]: ThreadedAnvilChunkStorage (venus): All chunks are saved
minecraft  | [11:01:39] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
minecraft  | [11:01:39] [Server thread/INFO]: ThreadedAnvilChunkStorage (mars): All chunks are saved
minecraft  | [11:01:39] [Server thread/INFO]: ThreadedAnvilChunkStorage (twilight_forest): All chunks are saved
minecraft  | [11:01:39] [Server thread/INFO]: ThreadedAnvilChunkStorage (deeper_down_dimension): All chunks are saved
minecraft  | [11:01:39] [Server thread/INFO]: ThreadedAnvilChunkStorage (mars_orbit): All chunks are saved
minecraft  | [11:01:39] [Server thread/INFO]: ThreadedAnvilChunkStorage (mercury_orbit): All chunks are saved
minecraft  | [11:01:39] [Server thread/INFO]: ThreadedAnvilChunkStorage (moon): All chunks are saved
minecraft  | [11:01:39] [Server thread/INFO]: ThreadedAnvilChunkStorage (glacio): All chunks are saved
minecraft  | [11:01:39] [Server thread/INFO]: ThreadedAnvilChunkStorage (glacio_orbit): All chunks are saved
minecraft  | [11:01:39] [Server thread/INFO]: ThreadedAnvilChunkStorage (earth_orbit): All chunks are saved
minecraft  | [11:01:39] [Server thread/INFO]: ThreadedAnvilChunkStorage (glassocean): All chunks are saved
```

Stacktrace:  https://pastebin.com/FDcBxfPc

docker-compose.yml:
```
version: '3'

services:
  minecraft:
    image: itzg/minecraft-server:java17
    container_name: minecraft
    ports:
      - "25565:25565"
    volumes:
      - "./mc:/data"
      - ./modpacks:/modpacks:ro
    environment:
      - EULA=TRUE
      - MEMORY=8G
      - TYPE=AUTO_CURSEFORGE
      - CF_PAGE_URL=https://www.curseforge.com/minecraft/modpacks/statech-industry
      - CF_API_KEY=${CF_API_KEY}
    tty: true
    stdin_open: true    
    restart: always
```

----
Steps to replicate:

1. Copy the docker-compose.yml definition into a docker-compose.yml
2. `docker compose up -d`
3. Watch as it crashes at the last step.

**Comment by bashbers** [comment]
I excluded the memoryleakfix mod from loading and now it's working as intended. I think one of the devs should look into this

**Comment by TheStaticVoid** [comment]
wait my bad I didn't see you wanted to include a docker config. I'm not too familiar with it, but it could be a nice alternative to having to provide server files.
