### ISSUE TITLE
Statech Industry not opening

### ISSUE THREAD

**Issue by Tecton121** [TheStaticVoid/StaTech-Industry#380]
i cant open sta tech industry, as everytime i do in the command log thing it says the minecraft crashed and i cant fix it. Logs below

[0
[09/08/2023 16:57:34 PM] Caused by: java.lang.RuntimeException: There were KubeJS startup script syntax errors! See logs/kubejs/startup.log for more info
[09/08/2023 16:57:34 PM] 	at dev.latvian.mods.kubejs.KubeJS.loadComplete(KubeJS.java:228)
[09/08/2023 16:57:34 PM] 	at dev.latvian.mods.kubejs.fabric.KubeJSFabric.onInitializeClient(KubeJSFabric.java:56)
[09/08/2023 16:57:34 PM] 	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
[09/08/2023 16:57:34 PM] 	... 8 more
[09/08/2023 16:57:34 PM] 
[09/08/2023 16:57:34 PM] 
[09/08/2023 16:57:34 PM] A detailed walkthrough of the error, its code path and all known details is as follows:
[09/08/2023 16:57:34 PM] ---------------------------------------------------------------------------------------
[09/08/2023 16:57:34 PM] 
[09/08/2023 16:57:34 PM] -- Head --
[09/08/2023 16:57:34 PM] Thread: Render thread
[09/08/2023 16:57:34 PM] Stacktrace:
[09/08/2023 16:57:34 PM] 	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
[09/08/2023 16:57:34 PM] 	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
[09/08/2023 16:57:34 PM] 	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
[09/08/2023 16:57:34 PM] 	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
[09/08/2023 16:57:34 PM] 	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
[09/08/2023 16:57:34 PM] 	at net.minecraft.class_310.<init>(class_310.java:459)
[09/08/2023 16:57:34 PM] Mixins in Stacktrace:
[09/08/2023 16:57:34 PM] 	net.minecraft.class_310:
[09/08/2023 16:57:34 PM] 		com.illusivesoulworks.spectrelib.mixin.SpectreLibMixinMinecraft (spectrelib.mixins.json)
[09/08/2023 16:57:34 PM] 		com.hrznstudio.emojiful.mixin.MinecraftEmojifulMixin (emojiful.mixins.json)
[09/08/2023 16:57:34 PM] 		de.keksuccino.konkrete.mixin.mixins.client.MixinMinecraft (konkrete.mixin.json)
[09/08/2023 16:57:34 PM] 		dev.sterner.geocluster.mixin.MinecraftClientMixin (geocluster.mixins.json)
[09/08/2023 16:57:34 PM] 		eu.pb4.polymer.mixin.client.MinecraftClientMixin (polymer.mixins.json)
[09/08/2023 16:57:34 PM] 		randommcsomethin.fallingleaves.mixin.MinecraftClientMixin (fallingleaves.mixins.json)
[09/08/2023 16:57:34 PM] 		tschipp.carryon.mixin.MinecraftMixin (carryon.mixins.json)
[09/08/2023 16:57:34 PM] 		dan200.computercraft.fabric.mixin.MixinMinecraft (computercraft.mixins.json)
[09/08/2023 16:57:34 PM] 		dev.architectury.mixin.fabric.client.MixinMinecraft (architectury.mixins.json)
[09/08/2023 16:57:34 PM] 		com.spanser.reacharound.mixin.client.MinecraftClientMixin (reacharound.mixins.json)
[09/08/2023 16:57:34 PM] 		zone.rong.cleancut.mixin.MinecraftClientMixin (cleancut.mixins.json)
[09/08/2023 16:57:34 PM] 		dev.lambdaurora.lambdynlights.mixin.MinecraftClientMixin (lambdynlights.mixins.json)
[09/08/2023 16:57:34 PM] 		bre2el.fpsreducer.mixin.MinecraftClientMixin (fpsreducer.json)
[09/08/2023 16:57:34 PM] 		io.github.fabricators_of_create.porting_lib.mixin.client.MinecraftMixinModelLoader (porting_lib_model_loader.mixins.json)
[09/08/2023 16:57:34 PM] 		dev.latvian.mods.kubejs.core.mixin.common.MinecraftMixin (kubejs-common.mixins.json)
[09/08/2023 16:57:34 PM] 		net.elidhan.anim_guns.mixin.client.MinecraftClientMixin (anim_guns.mixins.json)
[09/08/2023 16:57:34 PM] 		org.embeddedt.modernfix.common.mixin.feature.measure_time.MinecraftMixin (modernfix-common.mixins.json)
[09/08/2023 16:57:34 PM] 		shetiphian.core.mixins.SPC_ItemColor_Accessor (shetiphiancore.mixins.json)
[09/08/2023 16:57:34 PM] 		me.flashyreese.mods.sodiumextra.mixin.gui.MinecraftClientAccessor (sodium-extra.mixins.json)
[09/08/2023 16:57:34 PM] 		com.anthonyhilyard.prism.mixin.MinecraftMixin (prism.mixins.json)
[09/08/2023 16:57:34 PM] 		net.darkhax.bookshelf.mixin.client.AccessorMinecraft (bookshelf.common.mixins.json)
[09/08/2023 16:57:34 PM] 		net.fabricmc.fabric.mixin.networking.client.accessor.MinecraftClientAccessor (fabric-networking-api-v1.client.mixins.json)
[09/08/2023 16:57:34 PM] 		io.github.fabricators_of_create.porting_lib.mixin.client.accessor.MinecraftAccessor (porting_lib_common.mixins.json)
[09/08/2023 16:57:34 PM] 		de.dafuqs.spectrum.mixin.client.MinecraftClientMixin (spectrum.mixins.json)
[09/08/2023 16:57:34 PM] 		tfar.dankstorage.mixin.MinecraftClientAccessor (dankstorage.mixins.json)
[09/08/2023 16:57:34 PM] 		net.coderbot.iris.mixin.MixinMinecraft_Images (mixins.iris.json)
[09/08/2023 16:57:34 PM] 		com.tterrag.blur.mixin.MixinMinecraftClient (mixins.blur.json)
[09/08/2023 16:57:34 PM] 		net.minecraftforge.mixin.client.MinecraftMixin (forgeconfigapiport.fabric.mixins.json)
[09/08/2023 16:57:34 PM] 		vazkii.patchouli.mixin.client.MixinMinecraft (patchouli_fabric.mixins.json)
[09/08/2023 16:57:34 PM] 		net.bettercombat.mixin.client.MinecraftClientAccessor (bettercombat.mixins.json)
[09/08/2023 16:57:34 PM] 		io.github.tropheusj.dripstone_fluid_lib.mixin.MinecraftClientMixin (dripstone_fluid_lib.mixins.json)
[09/08/2023 16:57:34 PM] 		malte0811.ferritecore.mixin.fabric.MinecraftMixin (ferritecore.fabric.mixin.json)
[09/08/2023 16:57:34 PM] 		ca.fxco.memoryleakfix.mixin.hugeScreenshotLeak.Minecraft_screenshotMixin (memoryleakfix.mixins.json)
[09/08/2023 16:57:34 PM] 		org.embeddedt.modernfix.common.mixin.bugfix.concurrency.MinecraftMixin (modernfix-common.mixins.json)
[09/08/2023 16:57:34 PM] 		de.dafuqs.revelationary.mixin.client.MinecraftClientMixin (revelationary.mixins.json)
[09/08/2023 16:57:34 PM] 		me.axieum.mcmod.authme.mixin.MinecraftClientAccessor (authme.mixins.json)
[09/08/2023 16:57:34 PM] 		betteradvancements.mixin.MinecraftMixin (betteradvancements.mixins.json)
[09/08/2023 16:57:34 PM] 		ca.fxco.memoryleakfix.mixin.customPayloadLeak.Minecraft_freeBufferMixin (memoryleakfix-fabric.mixins.json)
[09/08/2023 16:57:34 PM] 		org.anti_ad.mc.ipnext.mixin.MixinMinecraftClient (mixins.ipnext.json)
[09/08/2023 16:57:34 PM] 		io.wispforest.owo.mixin.ui.MinecraftClientMixin (owo.mixins.json)
[09/08/2023 16:57:34 PM] 		net.fabricmc.fabric.mixin.event.interaction.client.MinecraftClientMixin (fabric-events-interaction-v0.client.mixins.json)
[09/08/2023 16:57:34 PM] 		appeng.mixins.BlockBreakParticleMixin (ae2.mixins.json)
[09/08/2023 16:57:34 PM] 		com.natamus.collective.fabric.mixin.MinecraftMixin (collective_fabric.mixins.json)
[09/08/2023 16:57:34 PM] 		me.lucko.spark.fabric.mixin.MinecraftClientAccessor (spark.mixins.json)
[09/08/2023 16:57:34 PM] 		io.github.fabricators_of_create.porting_lib.mixin.client.MinecraftMixin (porting_lib_base.mixins.json)
[09/08/2023 16:57:34 PM] 		draylar.omegaconfig.mixin.ClientMixin (omega-config.mixins.json)
[09/08/2023 16:57:34 PM] 		com.blamejared.controlling.mixin.OpenGuiMixin (controlling.fabric.mixins.json)
[09/08/2023 16:57:34 PM] 		ca.fxco.memoryleakfix.mixin.spongePoweredLeak.Minecraft_clientLoadedMixin (memoryleakfix-fabric.mixins.json)
[09/08/2023 16:57:34 PM] 		com.jozufozu.flywheel.fabric.mixin.MinecraftMixin (flywheel.fabric.mixins.json)
[09/08/2023 16:57:34 PM] 		journeymap.common.mixin.client.MinecraftMixin (journeymap.mixins.json)
[09/08/2023 16:57:34 PM] 		me.shedaniel.cloth.mixin.client.events.MixinMinecraftClient (cloth-client-events-v0.mixins.json)
[09/08/2023 16:57:34 PM] 		net.spell_engine.mixin.client.action_impair.MinecraftClientActionImpairing (spell_engine.mixins.json)
[09/08/2023 16:57:34 PM] 		net.blay09.mods.balm.mixin.MinecraftMixin (balm.mixins.json)
[09/08/2023 16:57:34 PM] 		de.keksuccino.fancymenu.mixin.client.IMixinMinecraft (fancymenu.general.mixin.json)
[09/08/2023 16:57:34 PM] 		me.jellysquid.mods.sodium.mixin.core.MixinMinecraftClient (sodium.mixins.json)
[09/08/2023 16:57:34 PM] 		dzwdz.chat_heads.mixin.MinecraftMixin (chat_heads.mixins.json)
[09/08/2023 16:57:34 PM] 		tfar.dankstorage.mixin.MinecraftClientMixin (dankstorage.mixins.json)
[09/08/2023 16:57:34 PM] 		net.fabricmc.fabric.mixin.event.lifecycle.client.MinecraftClientMixin (fabric-lifecycle-events-v1.client.mixins.json)
[09/08/2023 16:57:34 PM] 		org.embeddedt.modernfix.common.mixin.perf.blast_search_trees.MinecraftMixin (modernfix-common.mixins.json)
[09/08/2023 16:57:34 PM] 		com.simibubi.create.foundation.mixin.client.WindowResizeMixin (create.mixins.json)
[09/08/2023 16:57:34 PM] 		com.jozufozu.flywheel.mixin.PausedPartialTickAccessor (flywheel.mixins.json)
[09/08/2023 16:57:34 PM] 		io.wispforest.owo.mixin.MinecraftClientMixin (owo.mixins.json)
[09/08/2023 16:57:34 PM] 		ladysnake.satin.mixin.client.event.MinecraftClientMixin (mixins.satin.client.json)
[09/08/2023 16:57:34 PM] 		de.keksuccino.fancymenu.mixin.client.MixinMinecraft (fancymenu.general.mixin.json)
[09/08/2023 16:57:34 PM] 		net.spell_engine.mixin.client.control.MinecraftClientMixin (spell_engine.mixins.json)
[09/08/2023 16:57:34 PM] 		ca.lukegrahamlandry.travelstaff.mixin.MinecraftMixin (travelstaff.mixins.json)
[09/08/2023 16:57:34 PM] 		net.fabricmc.fabric.mixin.datagen.client.MinecraftClientMixin (fabric-data-generation-api-v1.client.mixins.json)
[09/08/2023 16:57:34 PM] 		net.spellbladenext.fabric.mixin.InteractMixin (spellbladenext.mixins.json)
[09/08/2023 16:57:34 PM] 		dlovin.inventoryhud.mixin.PlayerMixin (inventoryhud.mixins.json)
[09/08/2023 16:57:34 PM] 		com.railwayteam.railways.mixin.conductor_possession.MixinMinecraft (railways-common.mixins.json)
[09/08/2023 16:57:34 PM] 		net.coderbot.iris.mixin.MixinMinecraft_Keybinds (mixins.iris.json)
[09/08/2023 16:57:34 PM] 		com.hrznstudio.emojiful.mixin.fabric.ScreenEmojifulMixin (emojiful.fabric.mixins.json)
[09/08/2023 16:57:34 PM] 		appeng.mixins.PickColorMixin (ae2.mixins.json)
[09/08/2023 16:57:34 PM] 		dev.lambdaurora.spruceui.mixin.MinecraftClientMixin (spruceui.mixins.json)
[09/08/2023 16:57:34 PM] 		net.bettercombat.mixin.client.MinecraftClientInject (bettercombat.mixins.json)
[09/08/2023 16:57:34 PM] 		io.grayray75.fabric.norecipebook.mixin.MixinMinecraftClient (norecipebook.mixins.json)
[09/08/2023 16:57:34 PM] 		com.supermartijn642.core.mixin.MinecraftMixin (supermartijn642corelib.mixins.json)
[09/08/2023 16:57:34 PM] 		io.github.thecsdev.tcdcommons.client.mixin.events.MixinMinecraftClient (tcdcommons.client.mixin.events.json)
[09/08/2023 16:57:34 PM] 		org.embeddedt.modernfix.fabric.mixin.feature.measure_time.MinecraftMixin_Fabric (modernfix-fabric.mixins.json)
[09/08/2023 16:57:34 PM] 		squeek.appleskin.mixin.MinecraftClientMixin (appleskin.mixins.json)
[09/08/2023 16:57:34 PM] 		org.embeddedt.modernfix.fabric.mixin.core.MCMixin_Fabric (modernfix-fabric.mixins.json)
[09/08/2023 16:57:34 PM] 		net.fabricmc.fabric.mixin.screen.MinecraftClientMixin (fabric-screen-api-v1.mixins.json)
[09/08/2023 16:57:34 PM] 		ca.fxco.memoryleakfix.mixin.targetEntityLeak.Minecraft_targetClearMixin (memoryleakfix.mixins.json)
[09/08/2023 16:57:34 PM] 		com.anthonyhilyard.iceberg.mixin.MinecraftMixin (iceberg.mixins.json)
[09/08/2023 16:57:34 PM] 		de.maxhenkel.voicechat.mixin.MinecraftMixin (voicechat.mixins.json)
[09/08/2023 16:57:34 PM] 		net.fabricmc.fabric.mixin.registry.sync.client.MinecraftClientMixin (fabric-registry-sync-v0.client.mixins.json)
[09/08/2023 16:57:34 PM] 		net.coderbot.iris.mixin.MixinMinecraft_PipelineManagement (mixins.iris.json)
[09/08/2023 16:57:34 PM] 		org.embeddedt.modernfix.common.mixin.perf.dedicated_reload_executor.MinecraftMixin (modernfix-common.mixins.json)
[09/08/2023 16:57:34 PM] 		fuzs.puzzleslib.mixin.client.accessor.MinecraftFabricAccessor (puzzleslib.fabric.mixins.json)
[09/08/2023 16:57:34 PM] 		com.teampotato.redirectionor.mixin.client.MinecraftMixin (redirectionor-common.mixins.json)
[09/08/2023 16:57:34 PM] 
[09/08/2023 16:57:34 PM] #@!@# Game crashed! Crash report saved to: #@!@# **USERSDIR**\instances\StaTechIndustry\crash-reports\crash-2023-08-09_16.57.34-client.txt
[09/08/2023 16:57:35 PM] Oh no. Minecraft crashed. Please check the logs for any errors and provide these logs when asking for support.
[09/08/2023 16:57:35 PM] Checking for updated files!
[09/08/2023 16:57:35 PM] Checking for updates to CurseForge instances
[09/08/2023 16:57:39 PM] Copied Log to clipboard

**Comment by Tecton121** [comment]
i couldn't fit the entire log_

**Comment by TheStaticVoid** [comment]
Please post your `logs/kubejs/startup.log` file

**Comment by TheStaticVoid** [comment]
closing as stale
