### ISSUE TITLE
java.lang.IllegalStateException: BufferBuilder not started

### ISSUE THREAD

**Issue by seregatipich** [TheStaticVoid/StaTech-Industry#513]
When attempting to break a Quad Drawer that contains "Arcane Rob Top," the client immediately crashes, producing a ```java.lang.IllegalStateException: BufferBuilder``` not started error. Crash log suggests a compatibility or rendering pipeline issue involving Extended Drawers, Sodium, Indium, and/or Iris. It's related to the block’s contents. 
To reproduce:
1. Place a Quad Drawer and insert "Arcane Rob Top" into it.
2. Attempt to break the drawer.
-> The client crashes with the mentioned exception.

```
---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 2024-12-12 23:07:53
Description: Rendering Block Entity

java.lang.IllegalStateException: BufferBuilder not started
	at net.minecraft.class_287.method_22900(class_287.java:416)
	at net.minecraft.class_4584.method_22912(class_4584.java:18)
	at net.minecraft.class_4583.method_1344(class_4583.java:68)
	at net.minecraft.class_4720$class_4589.method_1344(class_4720.java:85)
	at me.jellysquid.mods.sodium.client.model.vertex.formats.quad.writer.QuadVertexWriterFallback.writeQuad(QuadVertexWriterFallback.java:23)
	at me.jellysquid.mods.sodium.client.model.vertex.formats.quad.QuadVertexSink.writeQuad(QuadVertexSink.java:42)
	at io.github.mattidragon.extendeddrawers.client.renderer.AbstractDrawerBlockEntityRenderer.renderItem(AbstractDrawerBlockEntityRenderer.java:112)
	at io.github.mattidragon.extendeddrawers.client.renderer.AbstractDrawerBlockEntityRenderer.renderSlot(AbstractDrawerBlockEntityRenderer.java:56)
	at io.github.mattidragon.extendeddrawers.client.renderer.DrawerBlockEntityRenderer.renderSlot(DrawerBlockEntityRenderer.java:82)
	at io.github.mattidragon.extendeddrawers.client.renderer.DrawerBlockEntityRenderer.render(DrawerBlockEntityRenderer.java:65)

-- Block Entity Details --
Details:
	Name: extended_drawers:drawer
	Block: Block{extended_drawers:quad_drawer}[facing=east]

-- System Details --
Details:
	Minecraft Version: 1.19.2
	Fabric Loader: 0.15.7
	Java Version: 17.0.8
	Operating System: Windows 10 (x64)
	CPU: Intel(R) Core(TM) i5-14600KF
	GPU: NVIDIA GeForce RTX 4070 Ti
	Memory: 268 MB / 2834 MB (Max: 4096 MB)
	Allocated: 4096 MB

-- Affected Mods --
Key Mods Present:
	sodium: 0.4.4
	fabric-api: 0.77.0
	iris: 1.6.11
	extended_drawers: 1.4.5
```

**Comment by TheStaticVoid** [comment]
issue with how the drawers render items that i can't remedy on the pack-side. not sure if the dev for the drawer mod works on 1.19.2 anymore either.
